esphome:
  name: iot_mh_led
  platform: ESP8266
  board: esp8285

wifi:
  ssid: "chimera-iot"
  password: "fafc996b949b6d53800"

  manual_ip:
    static_ip: 192.168.69.101
    gateway: 192.168.1.1
    subnet: 255.255.0.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Powermon Fallback Hotspot"
    password: "d3ZBU8Kih1RN"

captive_portal:

api:
  password: "fafc996b949b6d53800"

mqtt:
  broker: 192.168.1.117
  username: DVES_USER
  password: DVES_PASSWORD

logger:

ota:

light:
  - platform: rgb
    name: "iot_mh_led"
    red: mh_led_1
    green: mh_led_2
    blue: mh_led_3
output:
  - platform: esp8266_pwm
    id: mh_led_1
    pin: GPIO5
  - platform: esp8266_pwm
    id: mh_led_2
    pin: GPIO12
  - platform: esp8266_pwm
    id: mh_led_3
    pin: GPIO13

