esphome:
  name: wp6_one
  platform: ESP32
  board: esp8285

wifi:
  ssid: "chimera-iot"
  password: "fafc996b949b6d53800"

  manual_ip:
    static_ip: 192.168.69.101
    gateway: 192.168.1.1
    subnet: 255.255.0.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Powermon Fallback Hotspot"
    password: "d3ZBU8Kih1RN"

captive_portal:

mqtt:
  broker: 192.168.1.117
  username: DVES_USER
  password: DVES_PASSWORD

logger:

ota:

binary_sensor:
  - { "platform": "gpio"; "name": "WP6 Button1"; "pin": "GPIO3"; }
  - { "platform": "gpio"; "name": "WP6 Led1i";   "pin": "GPIO12"; }

output:
  - { "platform": "esp8266_pwn"; "id": "led1i"; pin: "GPIO13"; }
  - { "platform": "esp8266_pwn"; "id": "led2i"; pin: "GPIO14"; }

light:
  - platform: monochromatic

