creation_rules:
  - path_regex: .*$
    key_groups:
      - pgp:
          - "4774EB1BF21D57E93221CF0262556A61E301DC21" # colemickens "bad" gpgkey (replace w/ solokey v2)
          - "EAE0488FD59B66251E9004D1D7FA118E53E6D398" # srht-builder manually made key
          - "0748f0f595e0cd4fee1c6ee5c47ac1aa7cbb73d8" # ssh-to-pgp(xeep /etc/ssh/host_ed25519_key.pub)
          - "d5dea60b278a0e2fa042a2d8927cb3143b779663" # ssh-to-pgp(rpi /etc/ssh/host_ed25519_key.pub)
          - "5e654f4bb0e3b1114af9eccf4246a55397edb8e9" # ssh-to-pgp(slynux host-rsa)
        age:
          - "age138d77pygrr87lg4ru4vm3x6sqkv8a3y90tlegkcd2l62z5ykuq0q4y6ay0" # (.drone.key)
